server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URL}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: security-service-public
          uri: lb://security-service
          predicates:
            - Path=/auth/**, /oauth2/**, /login/oauth2/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                secured: false

        - id: quantity-measurement-service
          uri: lb://quantity-measurement-app
          predicates:
            - Path=/api/v1/quantities/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                secured: true

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
